apiVersion: apps/v1
kind: Deployment
metadata:
  name: age-calculator-frontend
  labels:
    app: age-calculator
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: age-calculator
      component: frontend
  template:
    metadata:
      labels:
        app: age-calculator
        component: frontend
    spec:
      containers:
      - name: frontend
        image: age-calculator-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4500
          name: http
        env:
        - name: VITE_API_URL
          value: "http://192.168.49.2:30400"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4500
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 4500
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: age-calculator
    component: frontend
spec:
  type: NodePort
  selector:
    app: age-calculator
    component: frontend
  ports:
  - port: 4500
    targetPort: 4500
    nodePort: 30450
    protocol: TCP
    name: http
